# Generated by Django 3.0.5 on 2020-04-06 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200406_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='teacher_code',
            field=models.CharField(blank=True, default='35321341', max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_list', models.CharField(default='', max_length=1000)),
                ('teacher', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Teacher')),
            ],
        ),
    ]
