# Generated by Django 3.0.5 on 2020-04-10 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_code', models.CharField(blank=True, default='22652781', max_length=8, unique=True)),
                ('admin_code', models.CharField(blank=True, default='803227927', max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('username', models.CharField(default='not set yet', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('school', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.School')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_link', models.CharField(max_length=200)),
                ('origin_class', models.CharField(max_length=10)),
                ('school', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.School')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_list', models.CharField(blank=True, default='', max_length=1000)),
                ('teacher', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Teacher')),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
    ]
