# Generated by Django 3.0.5 on 2020-05-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_list', models.CharField(blank=True, default='', max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_code', models.CharField(blank=True, default='25618723', max_length=8, unique=True)),
                ('admin_code', models.CharField(blank=True, default='657633991', max_length=9, unique=True)),
                ('origin_class_list', models.CharField(blank=True, default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('student_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('username', models.CharField(default='not set yet', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('school', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.School')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('embedding_link', models.CharField(max_length=200)),
                ('origin_class', models.CharField(max_length=10)),
                ('school', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.School')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('dictionary', models.CharField(max_length=1000)),
                ('belonging_class', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Class')),
            ],
            options={
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Teacher'),
        ),
    ]
