# Generated by Django 3.0.5 on 2020-05-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='admin_code',
            field=models.CharField(blank=True, default='214440568', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacher_code',
            field=models.CharField(blank=True, default='38232176', max_length=8, unique=True),
        ),
    ]
