# Generated by Django 3.0.5 on 2020-05-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200510_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='admin_code',
            field=models.CharField(blank=True, default='512659844', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacher_code',
            field=models.CharField(blank=True, default='55486932', max_length=8, unique=True),
        ),
    ]
