# Generated by Django 3.0.5 on 2020-04-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200414_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='origin_class_list',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='school',
            name='admin_code',
            field=models.CharField(blank=True, default='219697483', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacher_code',
            field=models.CharField(blank=True, default='41694888', max_length=8, unique=True),
        ),
    ]
