# Generated by Django 3.0.5 on 2020-04-06 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200406_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 6, 26, 37, 624338), verbose_name='date published'),
        ),
    ]
