# Generated by Django 3.0.5 on 2020-05-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200510_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default='done', max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='admin_code',
            field=models.CharField(blank=True, default='302670299', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacher_code',
            field=models.CharField(blank=True, default='84136120', max_length=8, unique=True),
        ),
    ]
