# Generated by Django 3.0.5 on 2020-04-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200429_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='admin_code',
            field=models.CharField(blank=True, default='282508973', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='origin_class_list',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacher_code',
            field=models.CharField(blank=True, default='88426354', max_length=8, unique=True),
        ),
    ]
