# Generated by Django 3.0.5 on 2020-04-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200429_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('student_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='admin_code',
            field=models.CharField(blank=True, default='409245800', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacher_code',
            field=models.CharField(blank=True, default='36396350', max_length=8, unique=True),
        ),
    ]
