# Generated by Django 3.0.5 on 2020-04-06 06:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200406_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 6, 45, 4, 949511), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.School')),
            ],
        ),
    ]
