# Generated by Django 3.0.5 on 2020-05-03 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200430_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='admin_code',
            field=models.CharField(blank=True, default='425858307', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacher_code',
            field=models.CharField(blank=True, default='98070667', max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dictionary', models.CharField(max_length=1000)),
                ('origin_class', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Class')),
            ],
        ),
    ]
