# Generated by Django 3.0.5 on 2020-05-04 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200503_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('dictionary', models.CharField(max_length=1000)),
                ('belonging_class', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Class')),
            ],
            options={
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.AlterField(
            model_name='school',
            name='admin_code',
            field=models.CharField(blank=True, default='735834299', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacher_code',
            field=models.CharField(blank=True, default='57806015', max_length=8, unique=True),
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
