# Generated by Django 3.0.5 on 2020-04-06 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200406_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='teacher_code',
            field=models.CharField(blank=True, default='62972656', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 7, 7, 47, 16907), verbose_name='date published'),
        ),
    ]
