# Generated by Django 3.0.5 on 2020-04-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200406_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='teacher_code',
            field=models.CharField(blank=True, default='66706967', max_length=8, unique=True),
        ),
    ]
